#!/bin/bash

set -euo pipefail

PROJECT_DIR=$(dirname "$(realpath "$0")")
USER_ID=$(id -u "${USER}")
GROUP_ID=$(id -g "${USER}")

prepare_docker() {
    local silently=0
    if [[ $# -gt 0 ]]; then
        if [[ "$1" == "-s" || "$1" == "--silent" ]]; then
            silently=1
        fi
    fi

    # Build the docker image
    cd "$PROJECT_DIR/docker"
    if [[ $silently -eq 1 ]]; then
        docker build -t easyaccept . > /dev/null 2>&1
    else
        docker build -t easyaccept .
    fi
    cd "$PROJECT_DIR"
}

prepare_grammar() {
    mkdir -p "$PROJECT_DIR/.tmp/grammar/target"
    cp "$PROJECT_DIR/EasyScript.g4" "$PROJECT_DIR/.tmp/grammar/"
}

prepare_gui() {
    xhost +local:docker
}

java() {
    # Run the 'javac' command
    # shellcheck disable=SC2086
    docker run --rm -i -u "$USER_ID:$GROUP_ID" -v "$PROJECT_DIR:/work" -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY --entrypoint="java" easyaccept "$@"
}

javac() {
    # Run the 'javac' command
    docker run --rm -i -u "$USER_ID:$GROUP_ID" -v "$PROJECT_DIR:/work" --entrypoint="javac" easyaccept "$@"
}

antlr4() {
    # Run the 'antlr4' command
    java -Xmx500M -cp /usr/local/lib/antlr4-tool.jar org.antlr.v4.Tool "$@"
}

antlr4_parse() {
    # Run the 'antlr4-parse' command
    java -cp /usr/local/lib/antlr4-tool.jar:.tmp/grammar/target/ org.antlr.v4.gui.TestRig "$@"
}

prepare_java_grammar() {
    # Generate the grammar as Java files
    antlr4 -Dlanguage=Java .tmp/grammar/EasyScript.g4

    # Compile the grammar
    JAVA_FILES=$(find "$PROJECT_DIR"/.tmp/grammar -name "*.java" -print0 | tr '\0' ' ')
    JAVA_FILES=${JAVA_FILES//"$PROJECT_DIR"\//}
    # shellcheck disable=SC2086
    javac -cp /usr/local/lib/antlr4-tool.jar -d .tmp/grammar/target $JAVA_FILES
}

parse_arguments() {
    local help_requested=0
    local command_requested=""

    while [[ -z "$command_requested" && "$#" -gt 0 ]]; do
        case $1 in
            -h|--help)
                help_requested=1
                shift
                ;;
            *)
                command_requested=$1
                shift
                break
                ;;
        esac
    done

    if [[ $help_requested -eq 1 ]]; then
        case $command_requested in
            generate)
                echo "Usage: ./easy generate <language> [-o | --output <output_directory>] [-p | --package <package_name>] [--visitor] [--listener]"
                echo
                echo "Generate the grammar on specified language. Supported languages: csharp"
                echo "Can specify output directory with -o or --output option."
                echo "Can specify library package name with -p or --package option."
                echo "By default, does not generate visitor or listener. To generate them, add --visitor and/or --listener options."
                ;;
            tree)
                echo "Usage: ./easy tree"
                echo
                echo "Parse the grammar and print the parse tree."
                ;;
            gui)
                echo "Usage: ./easy gui"
                echo
                echo "Launch the ANTLR4 GUI tool."
                ;;
            validate)
                echo "Usage: ./easy validate <file> [--objective]"
                echo
                echo "Validate the file against the grammar. If the file is valid, prints '✓ Input is VALID'. If the file is invalid, prints the error message and '✗ Input is INVALID'."
                echo "If the --objective option is provided, suppresses the docker output, the valid or invalid messages and only output the error message, if exists."
                ;;
            *)
                echo "Usage: ./easy [-h | --help] <command> [<args>]"
                echo
                echo "Commands:"
                echo "  generate   Generate the grammar on specified language"
                echo "  tree       Parse the grammar and print the parse tree"
                echo "  gui        Launch the ANTLR4 GUI tool"
                echo "  validate   Validate the file against the grammar"
                ;;
        esac

        exit
    fi

    if [[ -z "$command_requested" ]]; then
        echo "Error: No command provided."
        echo "Use -h or --help for usage information."
        exit 1
    fi

    case $command_requested in
        generate)
            if [[ "$#" -lt 1 ]]; then
                echo "Error: No language provided for 'generate' command."
                echo "Use -h or --help for usage information."
                exit 1
            fi

            local language=$1
            shift

            local output_directory=""
            local package_instruction=""
            local visitor_instruction="-no-visitor"
            local listener_instruction="-no-listener"

            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    -o|--output)
                        if [[ "$#" -lt 2 ]]; then
                            echo "Error: No output directory provided after '$1'."
                            echo "Use -h or --help for usage information."
                            exit 1
                        fi
                        output_directory=$2
                        shift 2
                        ;;
                    -p|--package)
                        if [[ "$#" -lt 2 ]]; then
                            echo "Error: No package name provided after '$1'."
                            echo "Use -h or --help for usage information."
                            exit 1
                        fi
                        package_instruction="-package $2"
                        shift 2
                        ;;
                    --visitor)
                        visitor_instruction="-visitor"
                        shift
                        ;;
                    --listener)
                        listener_instruction="-listener"
                        shift
                        ;;
                    *)
                        echo "Error: Unknown option '$1' for 'generate' command."
                        echo "Use -h or --help for usage information."
                        exit 1
                        ;;
                esac
            done

            if [[ "$language" == "csharp" ]]; then
                prepare_docker
                prepare_grammar

                # Generate the grammar as C# files
                # shellcheck disable=SC2086
                antlr4 -Dlanguage=CSharp $package_instruction $visitor_instruction $listener_instruction -o .tmp/grammar/csharp /work/EasyScript.g4

                # Move generated files to output directory if specified
                if [[ -n "$output_directory" ]]; then
                    mv .tmp/grammar/csharp "$output_directory"
                    echo "C# grammar files have been generated in '""$output_directory""'."
                else
                    echo "C# grammar files have been generated in '.tmp/grammar/csharp'."
                fi

                exit 0
            else
                echo "Error: Unsupported language '$language' for 'generate' command."
                echo "Use -h or --help for usage information."
                exit 1
            fi
            ;;
        tree)
            prepare_docker
            prepare_grammar
            prepare_java_grammar

            # Run the 'antlr4-parse' command
            echo "Write your input and press Ctrl+D to finish."
            antlr4_parse EasyScript easy -tree

            exit 0
            ;;
        gui)
            prepare_docker
            prepare_grammar
            prepare_gui
            prepare_java_grammar

            # Run the 'antlr4-parse' command
            echo "Write your input and press Ctrl+D to finish."
            antlr4_parse EasyScript easy -gui
            
            exit 0
            ;;
        validate)
            if [[ "$#" -lt 1 ]]; then
                echo "Error: No file provided for 'validate' command."
                echo "Use -h or --help for usage information."
                exit 1
            fi

            local file=$1
            shift

            if [[ ! -f "$file" ]]; then
                echo "Error: File '$file' does not exist."
                echo "Use -h or --help for usage information."
                exit 1
            fi

            # Move the file to .tmp/input folder
            mkdir -p "$PROJECT_DIR/.tmp/input"
            cp "$file" "$PROJECT_DIR/.tmp/input/"

            local objective_mode=0

            while [[ "$#" -gt 0 ]]; do
                case $1 in
                    --objective)
                        objective_mode=1
                        shift
                        ;;
                    *)
                        echo "Error: Unknown option '$1' for 'validate' command."
                        echo "Use -h or --help for usage information."
                        exit 1
                        ;;
                esac
            done

            if [[ $objective_mode -eq 1 ]]; then
                prepare_docker --silent
            else
                prepare_docker
            fi
            prepare_grammar
            prepare_java_grammar

            # Run the 'antlr4-parse' command
            # shellcheck disable=SC2046
            local output
            output=$(antlr4_parse EasyScript easy ".tmp/input/$(basename "$file")" 2>&1) || true
            echo "$output"

            # If starts with a "line [0-9]+:[0-9]+ " pattern, it's an error
            if [[ $output =~ ^line\ [0-9]+:[0-9]+ ]]; then
                if [[ $objective_mode -eq 0 ]]; then
                    echo "✗ Input is INVALID"
                fi
                exit 1
            fi

            if [[ $objective_mode -eq 0 ]]; then
                echo "✓ Input is VALID"
            fi
            exit 0
            ;;
        *)
            echo "Error: Unknown command '$command_requested'."
            echo "Use -h or --help for usage information."
            exit 1
            ;;
    esac
}

# Prepare temporary directory
mkdir -p "$PROJECT_DIR/.tmp"

parse_arguments "$@"
