#!/bin/bash

set -euo pipefail

PROJECT_DIR=$(dirname "$(realpath "$0")")
USER_ID=$(id -u "${USER}")
GROUP_ID=$(id -g "${USER}")

prepare_docker() {
    # Build the docker image
    cd "$PROJECT_DIR/docker"
    docker build -t easyaccept .
}

prepare_grammar() {
    mkdir -p "$PROJECT_DIR/.tmp/grammar/target"
    cp "$PROJECT_DIR/EasyScript.g4" "$PROJECT_DIR/.tmp/grammar/"
}

java() {
    # Run the 'javac' command
    docker run --rm -it -u "$USER_ID:$GROUP_ID" -v "$PROJECT_DIR:/work" --entrypoint="java" easyaccept "$@"
}

javac() {
    # Run the 'javac' command
    docker run --rm -it -u "$USER_ID:$GROUP_ID" -v "$PROJECT_DIR:/work" --entrypoint="javac" easyaccept "$@"
}

antlr4() {
    # Run the 'antlr4' command
    java -Xmx500M -cp /usr/local/lib/antlr4-tool.jar org.antlr.v4.Tool "$@"
}

antlr4_parse() {
    # Run the 'antlr4-parse' command
    java -cp /usr/local/lib/antlr4-tool.jar:.tmp/grammar/target/ org.antlr.v4.gui.TestRig "$@"
}

help() {
    echo
    echo "Usage:  $0 COMMAND"
    echo
    echo "Commands:"
    echo "  generate:csharp   Generate the grammar in C#"
    echo "  tree              Parse the grammar and print the parse tree"
    echo "  help              Display this help message"
    echo
}

# Prepare temporary directory
mkdir -p "$PROJECT_DIR/.tmp"

if [ "$#" -ne 1 ]; then
    help
    exit 1
fi

if [ "$1" == "help" ]; then
    help
    exit 0
fi

if [ "$1" == "generate:csharp" ]; then
    prepare_docker
    prepare_grammar

    # Generate the grammar as C# files
    antlr4 -Dlanguage=CSharp -o .tmp/grammar/csharp .tmp/grammar/EasyScript.g4

    echo "C# grammar files have been generated in '.tmp/grammar/csharp'."
    exit 0
fi

if [ "$1" == "tree" ]; then
    prepare_docker
    prepare_grammar

    # Generate the grammar as Java files
    antlr4 -Dlanguage=Java .tmp/grammar/EasyScript.g4

    # Compile the grammar
    JAVA_FILES=$(find "$PROJECT_DIR"/.tmp/grammar -name "*.java" -print0 | tr '\0' ' ')
    JAVA_FILES=${JAVA_FILES//"$PROJECT_DIR"\//}
    javac -cp /usr/local/lib/antlr4-tool.jar -d .tmp/grammar/target $JAVA_FILES

    # Run the 'antlr4-parse' command
    echo "Write your input and press Ctrl+D to finish."
    antlr4_parse EasyScript easy -tree

    exit 0
fi

echo "Invalid command '$1'."
echo "Run '$0 help' for usage."
exit 1